name: 京东极速版红包

on:
    workflow_dispatch:
    schedule:
        - cron: "0 16 1-3 3 *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【京东极速版红包】"
              run: |
                  node jd_speed_redpocke.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
